rabbitmq:
  image: "rabbitmq:3-management"
  hostname: "rabbitmq"
  environment:
  - RABBITMQ_DEFAULT_USER
  - RABBITMQ_DEFAULT_PASS
  ports:
    - "5672:5672"
    - "15672:15672"
  net: "host"
  container_name: appcivist_rabbitmq

appcivist-pb-client:
  build: ./appcivist-frontend
  ports:
    - "8080:8080"
  volumes:
  - /home/appcivist/production/appcivist-pb-client:/home/appcivist/production/appcivist-pb-client
  - /opt/appcivist/files:/opt/appcivist/files
  command: "./deploy.sh"
  net: "host"
  container_name: appcivist-pb-client

appcivist-plataform:
  build: ./appcivist-backend
  ports:
    - "9000:9000"
  volumes:
  - /home/yohanna/desarrollo/appcivist-platform:/home/appcivist/production/appcivist-platform
  command: "./deploy.sh"
  net: "host"
  volumes_from:
  - appcivist-pb-client
  container_name: appcivist-plataform
  environment:
  - APPCIVIST_CRYPTO
  - APPCIVIST_DB_DRIVER
  - APPCIVIST_DB_URL
  - POSTGRES_PASSWORD
  - POSTGRES_USER
  - APPCIVIST_CONTRIBUTION_FILES_PATH=
  - APPCIVIST_CONTRIBUTION_FILES_PATH_IS_ABSOLUTE
  - MAPBOX_API_TOKEN
  - IMGUR_CLIENT_ID
  - IMGUR_CLIENT_SECRET
  - AWS_ACCESS_KEY
  - AWS_SECRET_CODE
  - AWS_S3_BUCKET_NAME
  - AWS_S3_BUCKET_ENDPOINT
  - APPCIVIST_ETHERPAD_BASE_URL
  - ETHERPAD_API_KEY
  - APPCIVIST_NOTIFICATION_BASE_URL
  - APPCIVIST_NOTIFICATION_API_KEY
  - APPCIVIST_FORGOT_PASS_URL
  - APPCIVIST_RABBITMQ_HOST
  - APPCIVIST_RABBITMQ_PORT
  - APPCIVIST_RABBITMQ_ACTIVE
  - APPCIVIST_GOOGLE_CLIENT_ID
  - APPCIVIST_GOOGLE_CLIENT_SECRET
  - APPCIVIST_FACEBOOK_CLIENT_ID
  - APPCIVIST_FACEBOOK_CLIENT_SECRET
  - APPCIVIST_MAIL
  - APPCIVIST_MAIL_NAME
  - APPCIVIST_SMTP_HOST
  - APPCIVIST_SMTP_PORT
  - APPCIVIST_SMTP_SSL
  - APPCIVIST_SMTP_USER
  - APPCIVIST_SMTP_PASS
  - APPCIVIST_EASY_MAIL_MAIL
  - APPCIVIST_EASY_MAIL_NAME
  - RABBITMQ_DEFAULT_USER=user
  - RABBITMQ_DEFAULT_PASS=pass

appcivist-voting-api:
  build: ./appcivist-voting-api
  ports:
    - "5000:5000"
  volumes:
  - /home/appcivist/production/appcivist-voting-api:/home/appcivist/production/appcivist-voting-api
  command: bash -c "./deploy.sh && tail -f /dev/null"
  net: "host"
  environment:
  - POSTGRES_PASSWORD
  - POSTGRES_USER
  - POSTGRES_DB
  - VOTING_API_SECRET
  container_name: appcivist-voting-api

etherpad-lite:
  build: ./etherpad-lite
  ports:
    - "9001:9001"
  net: "host"
  environment:
  - ETHERPAD_DB_TYPE
  - ETHERPAD_DB_HOST
  - ETHERPAD_DB_USER
  - ETHERPAD_DB_PASSWORD
  - ETHERPAD_DB_NAME
  container_name: etherpad-lite

appcivist-usnb:
  build: ./usnb
  ports:
    - "3023:3023"
    - "3024:3024"
    - "3025:3025"
    - "3026:3026"
    - "3027:3027"
  command: bash -c "./deploy.sh production && tail -f /dev/null"
  net: "host"
  environment:
    - RABBITMQ_DEFAULT_USER
    - RABBITMQ_DEFAULT_PASS
    - USNB_EMAIL_HOST
    - USNB_EMAIL_PORT
    - USNB_EMAIL_USER
    - USNB_EMAIL_PASSWORD
    - USNB_FACEBOOK_USER
    - USNB_FACEBOOK_PASSWORD
  container_name: appcivist-usnb


db:
  build: ./postgres
  environment:
  - POSTGRES_PASSWORD
  - POSTGRES_USER
  - POSTGRES_DB
  volumes:
  - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
  - /var/lib/postgresql/data:/var/lib/postgresql/data
  net: "host"
  container_name: db

mongo:
  image: mongo:3.0.15
  volumes:
  - /var/lib/mongo/data:/data/db
  ports:
    - "27017:27017"
  net: "host"
  container_name: mongo
