version: "2"
services:
    rabbitmq:
      image: "rabbitmq:3-management"
      hostname: "rabbitmq"
      container_name: "rabbitmq"
      env_file: .env
      ports:
        - "5673:5672"
        - "15673:15672"
      container_name: appcivist_rabbitmq
      restart: always

    appcivist-pb-client:
      build: ./appcivist-frontend
      image: yolile/appcivist-pb-client
      depends_on:
      - appcivist-plataform
      ports:
        - "8000:8000"
      volumes:
      - ${FRONTEND_FILES}:/home/appcivist/production/appcivist-pb-client
      container_name: appcivist-pb-client
      env_file: .env

    appcivist-plataform:
      build: ./appcivist-backend
      stdin_open: true
      image: yolile/appcivist-backend
      depends_on:
        - db
        - rabbitmq
        - appcivist-voting-api
      command: sh deploy.sh
      links:
      - db
      - etherpad-lite
      - rabbitmq
      ports:
        - "9000:9000"
      volumes:
      - ${BACKEND_FILES}:/home/appcivist/production/appcivist-platform
      container_name: appcivist-plataform
      env_file: .env
      restart: always


    appcivist-voting-api:
      build: ./appcivist-voting-api
      ports:
        - "5000:5000"
      volumes:
      - ${VOTING_API_FILES}:/home/appcivist/production/appcivist-voting-api
      env_file: .env
      container_name: appcivist-voting-api
 
    etherpad-lite:
      build: ./etherpad-lite
      depends_on:
      - db
      links:
      - db
      ports:
        - "9001:9001"
      env_file: .env
      container_name: etherpad-lite
      restart: always
      
    db:
      build: ./postgres
      env_file: .env
      volumes:
      - /var/lib/postgresql/data5:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      container_name: db
      restart: always
