rabbitmq:
  image: "rabbitmq:3-management"
  hostname: "rabbitmq"
  env_file: .env
  ports:
    - "5672:5672"
    - "15672:15672"
  net: "host"
  container_name: appcivist_rabbitmq

apache:
  build: ./apache
  ports: 
    - "8080:8080"
    - "443:443"
  net: "host"
  volumes:
  - /opt/appcivist/files:/opt/appcivist/files
  - ./apache/confs:/etc/apache2/sites-available
  - ./apache/deploys:/var/www/html
  - ./apache/certs:/etc/apache2/certs
  container_name: apache

appcivist-pb-client:
  build: ./appcivist-frontend
  volumes:
  - /home/yohanna/desarrollo/appcivist-pb-client:/home/appcivist/production/appcivist-pb-client
  volumes_from:
  - apache
  command: "./deploy.sh"
  container_name: appcivist-pb-client

appcivist-plataform:
  build: ./appcivist-backend
  ports:
    - "9000:9000"
  volumes:
  - /home/appcivist/production/appcivist-platform:/home/appcivist/production/appcivist-platform
  command: "./deploy.sh"
  net: "host"
  volumes_from:
  - appcivist-pb-client
  container_name: appcivist-plataform
  env_file: .env

appcivist-voting-api:
  build: ./appcivist-voting-api
  ports:
    - "5000:5000"
  volumes:
  - /home/appcivist/production/appcivist-voting-api:/home/appcivist/production/appcivist-voting-api
  command: bash -c "./deploy.sh && tail -f /dev/null"
  net: "host"
  env_file: .env
  container_name: appcivist-voting-api

etherpad-lite:
  build: ./etherpad-lite
  ports:
    - "9001:9001"
  net: "host"
  env_file: .env
  container_name: etherpad-lite

appcivist-usnb:
  build: ./usnb
  ports:
    - "3023:3023"
    - "3024:3024"
    - "3025:3025"
    - "3026:3026"
    - "3027:3027"
  command: bash -c "./deploy.sh production && tail -f /dev/null"
  net: "host"
  env_file: .env
  container_name: appcivist-usnb
  
db:
  build: ./postgres
  env_file: .env
  volumes:
  - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
  - /var/lib/postgresql/data:/var/lib/postgresql/data
  net: "host"
  container_name: db

mongo:
  image: mongo:3.0.15
  volumes:
  - /var/lib/mongo/data:/data/db
  ports:
    - "27017:27017"
  net: "host"
  container_name: mongo
