rabbitmq:
  image: "rabbitmq:3-management"
  hostname: "rabbitmq"
  environment:
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
  ports:
    - "5672:5672"
    - "15672:15672"
  labels:
    NAME: "rabbitmq"


appcivist-pb-client:
  build: ./frontend
  ports:
    - "8080:8080"
  tty: true
  volumes:
  - /home/yohanna/desarrollo/appcivist-pb-client:/home/appcivist/production/appcivist-pb-client
  command: "./deploy.sh"


appcivist-plataform:
  build: ./appcivist-docker
  ports:
    - "9000:9000"
  tty: true
  volumes:
  - /home/yohanna/desarrollo/appcivist-platform:/home/appcivist/production/appcivist-platform
  command: "./deploy.sh"
  links:
  - rabbitmq