version: "2"
services:
    rabbitmq:
      image: "rabbitmq:3-management"
      hostname: "rabbitmq"
      env_file: .env
      ports:
        - "5673:5672"
        - "15673:15672"
      container_name: appcivist_rabbitmq
      restart: always

    apache:
      build: ./apache
      ports: 
        - "8081:8080"
        - "443:443"
        - "81:80"
      volumes:
      - ${APACHE_FILES}:/opt/appcivist/files
      - ${APACHE_DEPLOYS}:/var/www/html
      container_name: apache
      restart: always


    appcivist-pb-client:
      build: ./appcivist-frontend
      image: yolile/appcivist-pb-client
      depends_on:
      - appcivist-plataform
      volumes:
      - ${APACHE_DEPLOYS}:/var/www/html
      - ${FRONTEND_FILES}:/home/appcivist/production/appcivist-pb-client
      container_name: appcivist-pb-client
      env_file: .env

    appcivist-plataform:
      build: ./appcivist-backend
      image: yolile/appcivist-backend
      depends_on:
        - db
        - apache
        - rabbitmq
        - appcivist-voting-api
      command: sh deploy.sh & /etc/init.d/appcivist-backend start
      links:
      - db
      - etherpad-lite
      - rabbitmq
      ports:
        - "9000:9000"
      volumes:
      - ${BACKEND_FILES}:/home/appcivist/production/appcivist-platform
      - ${APACHE_FILES}:/opt/appcivist/files
      container_name: appcivist-plataform
      env_file: .env
      restart: always


    appcivist-voting-api:
      build: ./appcivist-voting-api
      depends_on:
      - apache
      ports:
        - "5000:5000"
      volumes:
      - ${VOTING_API_FILES}:/home/appcivist/production/appcivist-voting-api
      env_file: .env
      container_name: appcivist-voting-api
 
    etherpad-lite:
      build: ./etherpad-lite
      depends_on:
      - apache
      - db

      links:
      - db
      ports:
        - "9001:9001"
      env_file: .env
      container_name: etherpad-lite
      restart: always
      
    db:
      build: ./postgres
      env_file: .env
      volumes:
      - /var/lib/postgresql/data2:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      container_name: db
      restart: always
