#rabbitmq:
#  image: "rabbitmq:3-management"
#  hostname: "rabbitmq"
#  environment:
#    RABBITMQ_DEFAULT_USER: "rabbitmq"
#    RABBITMQ_DEFAULT_PASS: "rabbitmq"
#  ports:
#    - "5672:5672"
#    - "15672:15672"
#  labels:
#    NAME: "rabbitmq"
#  net: "host"
#

#
#appcivist-pb-client:
#  build: ./appcivist-frontend
#  ports:
#    - "8080:8080"
#  volumes:
#  - /home/yohanna/desarrollo/appcivist-pb-client:/home/appcivist/production/appcivist-pb-client
#  command: "./deploy.sh"
#  net: "host"
#
#
#appcivist-plataform:
#  build: ./appcivist-backend
#  ports:
#    - "9000:9000"
#  volumes:
#  - /home/yohanna/desarrollo/appcivist-platform:/home/appcivist/production/appcivist-platform
#  command: bash -c "/home/appcivist/production/appcivist-platform/./activator stage && /etc/init.d/appcivist-backend start"
#  net: "host"

#appcivist-voting-api:
#  build: ./appcivist-voting-api
#  ports:
#    - "5000:5000"
#  volumes:
#  - /home/yohanna/desarrollo/appcivist-voting-api:/home/appcivist/production/appcivist-voting-api
#  command: bash -c "./deploy.sh"
#  net: "host"

etherpad-lite:
  image: "pevtrick/etherpad-lite"
  ports:
    - "9001:9001"
  net: "host"
